### ISSUE TITLE
Assertion error in fast svd

### ISSUE THREAD

**Issue by bordeauxred** [Akella17/Deep-Bayesian-Quadrature-Policy-Optimization#1]
I am attempting to use DBQPG as policy gradient estimator with TRPO als policy gradient algorithm on a custom gym environment using:
python agent.py --env-name some_env --pg_algorithm TRPO --pg_estimator BQ

This resulted in the following error message:  

File "agent.py", line 170, in <module>
   likelihood, gp_mll, gp_value_optimizer, nn_value_optimizer)
 File "/home/Documents/DBQPO/optimization.py", line 184, in update_params
   policy_net)
 File "/home/Documents/DBQPO/fast_svd.py", line 23, in pca_U
   assert k > 0
AssertionError

**Comment by Akella17** [comment]
@bordeauxred Thanks for bringing this to my notice. I think you are running this code on an environment that is not defined in ```helper_config.json```. The default value of the argument ```svd_low_rank``` for environments that weren't defined in ```helper_config.json``` was **-1**. I have changed this default value to ```svd_low_rank = 50```.

Hope this resolves the issue.
